- Makefile
- README.md
- libs/printf/LICENSE
- libs/printf/printf.c
- libs/printf/printf.h
- src/core/boot.c
- src/core/debug.h
- src/core/isr.c
- src/core/syscall.c
- src/drivers/serial.c
- src/drivers/serial.h
- src/include/stdio.h
- src/kernel/kmain.c
- src/kernel/kshell.c
- src/kernel/panic.c
- src/libc/stdio.c
That will be more future-proof.
> Replace printf() impl with a lib

- src/core/boot.c
- src/core/debug.h
- src/kernel/kmain.c
- src/mmu/mmap.c
- src/mmu/mmap.h
This is the frame allocator from https://github.com/willdurand/willOS/pull/8
> Add frame allocator

- asm/1.start.asm
- src/core/boot.c
- src/core/boot.h
- src/kernel/kmain.c
- src/kernel/panic.c
- src/kernel/panic.h
- src/mmu/debug.h
- src/mmu/mmap.c
- src/mmu/mmap.h
- src/mmu/paging.c
- src/mmu/paging.h
Based on https://github.com/willdurand/willOS/pull/8 but cleaner, I guess.
> Start paging implementation

- .circleci/config.yml
- .gitignore
- Makefile
- src/libc/string/strlen.c
- test/libc/string/strdup.c
- test/libc/string/strlen.c
- test/libc/string/strncmp.c
- test/test.h
Output looks like this:
```
it returns the length of the string                                   [pass]
it handles empty string                                               [pass]
test/libc/string/strlen.c                           failures:  0 / total:  2
it returns 0 when strings are equal                                   [pass]
it works for empty strings                                            [pass]
it returns a non-zero value when strings are different                [pass]
it compares the N first characters                                    [pass]
test/libc/string/strncmp.c                          failures:  0 / total:  4
it duplicates string                                                  [pass]
it has similar size                                                   [pass] …
```
> Start adding some tests

- src/kernel/kshell.c
- userland/init/init.c
> Re-implement date command in init

- Makefile
- initrd/debug
- src/fs/debug.h
- src/fs/proc.c
- src/fs/proc.h
- src/fs/vfs.c
- src/kernel/kmain.c
- src/kernel/kshell.c
- test/fs/proc.c
I wanted to reimplement the `uptime` command in the `init` "shell". Linux uses files to find such information so I decided to implement a `proc` FS to expose some files with information.
> Add a new 'proc' filesystem

- src/include/string.h
- src/libc/string/strchr.c
- src/libc/string/strcmp.c
- src/libc/string/strspn.c
- src/libc/string/strtok.c
- test/libc/string/strchr.c
- test/libc/string/strcmp.c
- test/libc/string/strspn.c
- test/libc/string/strtok.c
> Add new c functions

- src/kernel/kmain.c
- src/mmu/paging.c
Fixes https://github.com/willdurand/willOS/issues/79
> Identity map initrd module

- src/mmu/frame.c
- src/mmu/frame.h
- src/mmu/paging.c
- src/mmu/paging.h
- test/mmu/paging.c
Fixes https://github.com/willdurand/willOS/issues/84
Fixes https://github.com/willdurand/willOS/issues/85
> Add frame_number_t/page_number_t types

- .circleci/config.yml
- .gitignore
- Dockerfile
- Makefile
- README.md
- linker.ld
- src/core/boot.c
- src/core/syscall.c
- src/fs/proc.c
- src/fs/tar.c
- src/kernel/kmain.c
- src/kernel/kshell.c
- src/libc/errno.c
- src/mmu/alloc.c
- src/mmu/alloc.h
- src/mmu/bitmap.h
- src/mmu/frame.c
- src/mmu/frame.h
- src/mmu/paging.c
- test/mmu/bitmap.c
- userland/Makefile.include
- userland/shell/main.c
Fixes https://github.com/willdurand/willOS/issues/90
> Fix bugs when building the kernel with the Docker toolchain

- .circleci/config.yml
- Dockerfile
- Makefile
- src/kernel/kmain.c
Fixes https://github.com/willdurand/willOS/issues/94
> Use multiboot command line to boot and exit in circle-ci

- Makefile
- src/fs/proc.c
- src/include/sys/types.h
- src/kernel/kshell.c
- test/fs/proc.c
- userland/meminfo/Makefile
- userland/meminfo/main.c
Fixes https://github.com/willdurand/willOS/issues/93
> Expose meminfo data via procfs

- src/mmu/paging.c
Fixes https://github.com/willdurand/willOS/issues/102
> Fix paging_init(): avoid overlap when remapping the kernel

- src/mmu/frame.c
- src/mmu/frame.h
- src/mmu/paging.c
- test/mmu/frame.c
Fixes https://github.com/willdurand/willOS/issues/86
> Make frame allocator more dynamic

- src/core/elf.c
- src/core/elf.h
Fixes https://github.com/willdurand/willOS/issues/106
> Simplify ELF loader

- src/kernel/kmain.c
- src/kernel/kshell.c
- src/net/arp.c
- src/net/arp.h
- src/net/ethernet.c
- src/net/ethernet.h
- src/net/net.c
- src/net/net.h
- add support for ARP protocol
- add static config
- init a network interface with this static config and the only configured ethercard
> Fully configure network (static)

- Makefile
- src/config/inish.c
- src/config/inish.ebnf
- src/config/inish.h
- test/config/inish.c
- test/config/test.inish
I wanted to use a configuration file for the network (static) config and I
thought it'd be fun to write a parser from scratch. inish is a config format
between ini and toml. We'll see how it goes.
> Introduce inish config format

- src/config/inish.c
- src/config/inish.h
- src/core/sys/syscall.c
- src/include/fcntl.h
- src/include/sys/syscall.h
- test/fs/tar.c
- userland/cat/main.c
- userland/hostname/main.c
- userland/meminfo/main.c
- userland/uptime/main.c
Fixes https://github.com/willdurand/willOS/issues/132
> Add fcntl.h

- src/config/inish.c
- src/core/sys/syscall.c
- src/include/errno.h
Fixes https://github.com/willdurand/willOS/issues/135
> Add checks for some file descriptor flags

- src/config/inish.c
- src/config/inish.h
- src/include/unistd.h
- userland/cat/main.c
- userland/hostname/main.c
- userland/meminfo/main.c
- userland/uptime/main.c
Fixes https://github.com/willdurand/willOS/issues/133
> Add unistd.h

- src/kernel/kshell.c
- src/net/arp.c
- src/net/ethernet.c
- src/net/ipv4.c
- src/net/ipv4.h
- src/net/net.h
Fixes https://github.com/willdurand/willOS/issues/122
> Add support for IPv4 and ICMPv4

- src/net/arp.c
- src/net/ethernet.c
> Reply to ARP requests when we can

- src/include/arpa/inet.h
- src/include/sys/socket.h
- src/net/arp.c
- src/net/ethernet.c
- src/net/ethernet.h
- src/net/ipv4.c
- src/net/udp.c
Fixes #146
---
Added `sys/socket.h` too.
> Add arpa/inet.h and sys/socket.h headers

- src/net/ipv4.c
- src/net/ipv4.h
- src/net/udp.c
- src/net/udp.h
> Use sockaddr_in for UDP and in_addr_t for IP

- src/include/arpa/inet.h
- src/kernel/kshell.c
- src/libc/arpa/inet_addr.c
- src/net/dns.c
- src/net/dns.h
- src/net/ipv4.c
- src/net/udp.c
> Add minimal yet working DNS support

- src/fs/debug.c
- src/net/dns.c
refs https://github.com/willdurand/willOS/issues/157
> Fix some compilation warnings

- Makefile
- initrd/etc/kernel.inish
- src/include/arpa/inet.h
- src/kernel/kmain.c
- src/libc/arpa/inet_ntoa2.c
- src/net/dhcp.c
- src/net/dhcp.h
- src/net/ipv4.c
- src/net/net.c
- src/net/net.h
- src/net/udp.c
- src/net/udp.h
> Implement DHCP

- src/kernel/kmain.c
Because this looks slightly nicer :p
> Add sub-steps in kmain boot sequence

- src/core/sys/recvfrom.c
- src/core/sys/sendto.c
- src/core/sys/socket.c
- src/core/sys/syscall.c
- src/core/sys/syscall.h
- src/include/errno.h
- src/include/sys/socket.h
- src/include/sys/syscall.h
- src/kernel/kshell.c
- src/libc/sys/open.c
- src/libc/sys/recvfrom.c
- src/libc/sys/sendto.c
- src/libc/sys/socket.c
- src/net/dns.c
- src/net/dns.h
- src/net/ipv4.c
- src/net/ipv4.h
- src/net/socket.c
- src/net/socket.h
- src/net/udp.c
- src/net/udp.h
- src/proc/descriptor.c
- src/proc/descriptor.h
Fixes https://github.com/willdurand/willOS/issues/147
> Implement socket, recvfrom, sendto syscalls and refactor IP/UDP/DNS

- userland/udp-client/Makefile
- userland/udp-client/main.c
- userland/udp-client/server.py
> Add udp-client userland program

- src/fs/debug.c
- src/fs/proc.c
- src/fs/sock.c
- src/fs/tar.c
- src/fs/vfs.c
- src/fs/vfs.h
- src/kernel/kshell.c
- src/sys/k_fstat.c
- src/sys/k_lseek.c
- test/fs/proc.c
- test/fs/sock.c
- test/fs/tar.c
Fixes https://github.com/willdurand/willOS/issues/178
> Rename stat_t to vfs_stat_t

- src/fs/proc.c
- src/fs/sock.c
- src/fs/tar.c
- src/fs/vfs.c
- src/fs/vfs.h
- src/kernel/kshell.c
- test/fs/proc.c
- test/fs/sock.c
- test/fs/tar.c
- test/fs/vfs.c
> Rename vfs_inode_type() to vfs_type()

- Makefile
- README.md
- include/sys/reboot.h
- src/asm/boot.asm
- src/asm/usermode.asm
- src/core/gdt.h
- src/core/idt.c
- src/core/idt.h
- src/core/isr.c
- src/core/register.h
- src/kernel/kmain.c
- src/kernel/kshell.c
- src/mmu/paging.c
- src/mmu/paging.h
- src/proc/usermode.h
- src/sys/k_reboot.c
- src/sys/k_syscall.c
- userland/boot-and-exit/Makefile
- userland/boot-and-exit/main.c
- userland/shell/main.c
> Switch to usermode

- Makefile
- include/errno.h
- include/sys/syscall.h
- src/asm/interrupts.asm
- src/asm/k_syscall.asm
- src/core/isr.c
- src/core/isr.h
- src/libc/asm/syscall.asm
- src/libc/sys/close.c
- src/libc/sys/fstat.c
- src/libc/sys/gethostbyname2.c
- src/libc/sys/gettimeofday.c
- src/libc/sys/lseek.c
- src/libc/sys/open.c
- src/libc/sys/read.c
- src/libc/sys/reboot.c
- src/libc/sys/recvfrom.c
- src/libc/sys/sendto.c
- src/libc/sys/socket.c
- src/libc/sys/test.c
- src/libc/sys/write.c
- src/sys/k_recvfrom.c
- src/sys/k_sendto.c
- src/sys/k_syscall.c
- src/sys/k_syscall.h
> Use syscall/sysret instead of interrupts for syscalls

- Makefile
- README.md
- src/kernel/kmain.c
- src/libc/asm/crt0.asm
- src/libc/start_main.c
- src/proc/usermode.h
- userland/Makefile.include
- userland/init/Makefile
- userland/init/main.c
Fixes https://github.com/willdurand/willOS/issues/197
Fixes https://github.com/willdurand/willOS/issues/202
> Add init userland program

- include/sys/syscall.h
- include/sys/types.h
- src/kernel/kmain.c
- src/libc/asm/crt0.asm
- src/libc/start_main.c
- src/libc/sys/execv.c
- src/proc/process.h
- src/sys/k_execv.c
- src/sys/k_syscall.c
- src/sys/k_syscall.h
- userland/init/main.c
- userland/shell/main.c
> Implement execv syscall

- src/asm/k_syscall.asm
Fixes https://github.com/willdurand/willOS/issues/208
> Fix syscall handler code

- Makefile
- src/arch/x86_64/fs/tar.c
- src/arch/x86_64/fs/vfs.c
refs https://github.com/willdurand/willOS/issues/273
> test: enable ASan, remove valgrind, fix two bugs

- Makefile
Fixes https://github.com/willdurand/willOS/issues/92
> Add -O2 to CFLAGS

- src/arch/x86_64/mmu/frame.c
This fixes an issue I found with these STR:
1. boot in kernel mode
2. run `cat /proc/meminfo` and write down the number of frames used
3. run `selftest`
4. run `cat /proc/meminfo` and write down the number of frames used
5. run `selftest`
6. run `cat /proc/meminfo` and write down the number of frames used
The number of frames used in (3) and (4) should be very close to each other,
and the number of frames used in (4) and (6) should be identical. Otherwise it
means we are leaking frames, and potentially marking frames in-use as "free" to
re-use again.
This is because the `allocated_frames` is set with `request` values, not
`frame_number`. We use `request` for good reasons (because there are holes in
memory IIRC).
This patch fixes the problem by introducing `frame_number_to_request()`.
> kernel: mmu: fix frame_deallocate() by looking up the request

- include/kernel/arch/panic.h
- include/kernel/panic.h
- src/kernel/panic.c
- tests/kernel/mmu/frame.c
- tests/kernel/mmu/paging.c
This patch also adds some documentation about this module.
> kernel: panic: main implementation is not arch-specific

- include/kernel/kmain.h
- src/kernel/arch/x86_64/kmain.c
- src/kernel/kmain.c
> kernel: handle command line parsing in kmain()

- include/kernel/init.h
- src/kernel/arch/x86_64/linker.ld
- src/kernel/kmain.c
> kernel: initcall: add initial implementation

- src/kernel/arch/x86_64/fs/dev/com1.c
- src/kernel/fs/dev/debug.c
- src/kernel/fs/dev/null.c
- src/kernel/fs/proc.c
- src/kernel/fs/sock.c
- src/kernel/fs/tar.c
- tests/kernel/fs/vfs.c
Fixes https://github.com/willdurand/ArvernOS/issues/390
> kernel: fs: use field names in drivers

- include/kernel/fs/sock.h
- src/kernel/fs/sock.c
Fixes https://github.com/willdurand/ArvernOS/issues/391
> kernel: fs: sock: make sock_fs_create() private

- include/kernel/fs/vfs.h
- src/kernel/fs/vfs.c
- src/kernel/kmain.c
> kernel: fs: fix vfs_init() prototype

- external/liballoc/liballoc.c
> external: liballoc: fix undefined behaviors

- external/dlmalloc/dlmalloc.c
- external/dlmalloc/dlmalloc.h
Version 2.8.6 downloaded from http://gee.cs.oswego.edu/pub/misc/ and splitted as per instructions in the C file.
> external: add dlmalloc

- .circleci/config.yml
- Makefile
- external/dlmalloc/dlmalloc.c
- external/dlmalloc/dlmalloc.h
- include/libc/stdlib.h
- src/kernel/arch/x86_64/mmu/alloc.c
> kernel: x86_64: add support for dlmalloc

- Makefile
- include/kernel/arch/kernel.h
- include/kernel/core/arm/atag.h
- include/kernel/core/mmio.h
- include/kernel/fs/vfs.h
- include/kernel/init.h
- include/kernel/keymap.h
- include/kernel/kmain.h
- include/kernel/kshell/kshell.h
- include/kernel/logging.h
- include/kernel/osinfo.h
- include/kernel/panic.h
- src/kernel/fs/proc/version.c
- src/kernel/kmain.c
- src/kernel/kshell/kshell.c
- src/kernel/kshell/kshell.h
> docs: add more docs in kernel headers

- src/kernel/arch/aarch32/arch/core.c
- src/kernel/arch/aarch32/arch/time.c
- src/kernel/arch/aarch32/asm/isr.asm
- src/kernel/arch/aarch32/board/licheepi-nano/arch/time.c
- src/kernel/arch/aarch32/board/licheepi-nano/board.h
- src/kernel/arch/aarch32/board/raspi2/Makefile.include
- src/kernel/arch/aarch32/board/raspi2/arch/time.c
- src/kernel/arch/aarch32/board/raspi2/asm/boot.asm
- src/kernel/arch/aarch32/board/raspi2/board.h
Fixes https://github.com/willdurand/ArvernOS/issues/508
> kernel: aarch32: raspi2: add basic support for interrupts and timer

- src/kernel/arch/aarch32/Makefile.include
- src/kernel/arch/aarch32/arch/kshell.c
- src/kernel/arch/aarch32/arch/sys.c
- src/kernel/arch/aarch32/asm/isr.asm
- src/kernel/arch/aarch32/asm/k_syscall.asm
- src/kernel/arch/aarch32/asm/macro-defs.asm
- src/libc/asm/aarch32/syscall.asm
Fixes https://github.com/willdurand/ArvernOS/issues/520
> kernel: aarch32: implement syscalls

- src/kernel/arch/aarch64/arch/kernel.c
- src/kernel/arch/aarch64/sys/k_semihosting.c
- src/kernel/arch/aarch64/sys/k_semihosting.h
Fixes https://github.com/willdurand/ArvernOS/issues/504
> kernel: aarch64: implement k_semihosting() (pseudo-)syscall

- include/kernel/sys/k_syscall.h
- include/libc/stdlib.h
- include/libc/sys/syscall.h
- src/kernel/sys/k_exit.c
- src/kernel/sys/k_syscall.c
- src/libc/start_main.c
- src/libc/sys/exit.c
refs https://github.com/willdurand/ArvernOS/issues/240
> kernel/libc: add exit syscall stub

- src/kernel/arch/x86_64/arch/panic.c
- stacktrace should include up to 16 function calls
- stacktrace should end when an address is not related to the kernel
> kernel: x86_64: add more checks to arch_kernel_dump_stacktrace()

- src/kernel/arch/x86_64/proc/process.c
- src/kernel/arch/x86_64/proc/process.h
This new approach is similar to the System V ABI.
> kernel: x86_64: refactor the process initial stack

- src/kernel/sys/k_read.c
This change has been extracted from https://github.com/willdurand/ArvernOS/pull/552
> kernel: sys: fix how we check flags in k_read()

- src/kernel/proc/descriptor.c
This change has been extracted from https://github.com/willdurand/ArvernOS/pull/552
> kernel: proc: fix checks in descriptor_udp_lookup()

- src/kernel/sys/k_write.c
- src/libc/putchar.c
This change has been extracted from https://github.com/willdurand/ArvernOS/pull/552
> kernel/libc: fix putchar()
