willdurand/ArvernOS

libs/liballoc/LICENSE, libs/liballoc/liballoc.c, libs/liballoc/liballoc.h, src/include/stdlib.h, src/kernel/kmain.c, src/kernel/kshell.c, src/mmu/alloc.c, src/mmu/alloc.h, src/mmu/paging.c, src/mmu/paging.h
Watermark allocators everywhere! So, I reused an existing lib named `liballoc`. It provides `malloc`, `free`, etc. for "free". That is maybe not the best heap allocator, but it actually works and there are many other things to "fix" before trying to implement an new heap allocator...
- the paging module works but not there are issues with high addresses it seems
- the frame allocator should really deallocate frames...
- the heap allocator should also unmap pages and release memory... For now, it does not do much and we panic ("out of memory") very quickly.
=> Heap memory allocator

src/fs/tar.c, test/fs/tar.c
Replaces #30 
Fixes #33
- It fixes tar_find_dir by checking the length of both strings when using `strncmp`
I did basically the same you did in #30, including the test. All tests pass, doing the following commands have the following results:
>> cat /inf
> no such file or directory
>> cat /info
> prints the content of info
>> cat /boo
> no such file or directory
>> cat /booo
> prints the content of booo
>> ls /bin/init
> bin/init is not a directory
>> ls /bin/ini
> no such file or directory
I wanted to work on something for willOS but I was tired from working on ELF loading shenanigans, so I figured I'd help you with this one bit. Thankfully my hipothesis was correct, and you simply had to check if the file paths had the same length before calling strncmp 😄
=> Fix tar_find_dir

src/kernel/kshell.c
This fixes an issue when we exit a program started in `kshell` or when we try to run a non-ELF file.
=> Return error when trying to execute a non-ELF file

Dockerfile, src/mmu/alloc.c, src/mmu/paging.c, src/mmu/paging.h
- It fixes some allocation issues with paging
- It adds new helpful methods to paging, which will be used for more accurately mapping things and avoiding page faults
- It fixes an issue where you could overwrite previous mapped pages when allocating with liballoc
=> Fix paging map/unmap logic and `liballoc_alloc`

src/core/boot.c, src/core/cmos.c, src/core/debug.h, src/core/syscall.c, src/drivers/screen.c, src/drivers/serial.c, src/fs/debug.c, src/fs/tar.c, src/fs/vfs.c, src/kernel/kmain.c, src/kernel/kshell.c, src/libc/string/strsep.c, src/libc/time/localtime.c, src/libc/time/strftime.c, src/mmu/bitmap.c, src/mmu/bitmap.h, src/mmu/paging.c
I started to evaluate clang-tidy/clang-format to automatically fix trivial mistakes and/or autoformat the code.
=> Cleanup some parts with clang-tidy

Makefile, src/kernel/kshell.c, src/libc/stackguard.c, userland/init/Makefile, userland/init/init.c
- It adds a stack smash protector that detects stack buffer overflows
- It adds an "overflow" kshell command for testing the protector
Base taken from https://wiki.osdev.org/Stack_Smashing_Protector with working example from https://en.wikipedia.org/wiki/Stack_buffer_overflow . 
The way stack buffer overflow basically works is that the compiler has support for a stack protector, and if we provide a couple fields, it's able to detect when we overwrite a memory area before returning a value.
An example that you can see in the previously posted link is something like this:
```c
char c[12];
strcpy(c, "12345678901234567890"); //Exceeds the 12 characters of the string
return 1; //Will cause the trigger here
```
I will test this in userland after posting this PR.
=> Added stack smash protector

src/core/elf.c, src/core/elf.h, src/mmu/paging.c, userland/init/Makefile
- It adds the paging changes from #34 (dependency)
- It fixes userland ELF loading
- It adds some useful data structures and helper methods to the elf files
- It increases the memory size of QEMU to 256MB due to errors
- It disables optimizations for userland bin
=> Fix ELF loader

.circleci/config.yml, Dockerfile
Fixes #48
It fixes the issue by providing a Docker image with working tools so one can run:
```
docker run --rm -v $(pwd):/app willos/toolchain make fmt
```
=> Require clang-format 9

src/mmu/alloc.c, src/mmu/alloc.h, test/mmu/bitmap.c
For some reasons, a few bits are set to `1` in the `allocated_pages` bitmap, even after `memset()`. I tried to reset all the bits with a loop and `bitmap_clear()` but all I got was a General Fault Protection... Let's make this allocator dumb for now.
=> Remove bugged bitmap usage in alloc

Makefile, src/include/stdio.h, src/include/stdlib.h, src/include/string.h, src/include/sys/types.h, src/libc/putchar.c, src/libc/stackguard.c, src/libc/string/strdup.c, userland/Makefile.include, userland/hostname/main.c, userland/shell/reboot.c
This patch also exposes `__willos__` in the userland programs so that we can
conditionally require header files (depending on the platform).
=> Fix libc/libk compilation

src/libc/asm/syscall.asm, src/libc/sys/recvfrom.c, src/libc/sys/sendto.c, src/sys/k_recvfrom.c, src/sys/k_sendto.c, src/sys/k_syscall.h
Fixes #200
---
We can now pass up to 6 parameters to a syscall.
=> Fix sendto()/recvfrom() syscalls

README.md, bochsrc.txt, src/asm/boot.asm, src/core/gdt.h, src/core/multiboot.c, src/core/multiboot.h, src/core/tss.c, src/core/tss.h, src/kernel/kmain.c, src/kernel/kshell.c, src/logging.h, src/mmu/alloc.c, src/mmu/frame.c, src/mmu/frame.h, src/mmu/paging.c, test/mmu/frame.c, userland/Makefile.include
Not directly related but also fixes #248 
---
I think this would be a better frame allocator because we'd skip all lower addresses and memory already used. It looks like it would reserve/skip ~2MB of memory (including the bitmap for the allocated frames). I think this is perfectly fine.
=> Refactor frame allocator and more

src/kshell/cat.c, src/kshell/kshell.c, src/kshell/kshell.h
The kshell builtin `cat` command was previously removed in commit 83a747243f9c34773bf661b64e965d9c57e48945.  The command is restored in this change.
Fixes: #242
=> Restore cat command to kshell

src/kshell/cat.c
The function `vfs_read` simply copies bytes to the buffer and does not add a null terminator.  To address this the number of bytes read is passed to `printf`.
=> Fix cat by passing bytes read to printf

.circleci/config.yml, Makefile, external/liballoc/liballoc.c, include/ubsan.h, src/arch/x86_64/core/tss.h, src/arch/x86_64/net/ntp.c, src/libc/arpa/inet_addr.c, src/libc/ubsan.c
Fixes #269
---
TODO: (maybe for a follow-up) find why `liballoc` raises type mismatches.
=> Add support for ubsan (Undefined Behavior Sanitization)

src/arch/x86_64/linker.ld
Reverts willdurand/willOS#276
This breaks `addr2line` and `llvm-symbolizer` because it removes the source code annotations.
=> Revert "linker: discard .debug* sections"

Makefile, Makefile.include, tools/fix-stacktrace.py
refs #275
---
Before:
```
DEBUG    | src/arch/x86_64/kshell/kshell.c:108:run_command(): command='selftest' argc=1
DEBUG    | src/arch/x86_64/kernel/panic.c:30:kernel_dump_stacktrace(): kernel stacktrace:
DEBUG    | src/arch/x86_64/kernel/panic.c:39:kernel_dump_stacktrace():   00000000001163B3
DEBUG    | src/arch/x86_64/kernel/panic.c:39:kernel_dump_stacktrace():   0000000000115941
DEBUG    | src/arch/x86_64/kernel/panic.c:39:kernel_dump_stacktrace():   0000000000115BE1
DEBUG    | src/arch/x86_64/kernel/panic.c:39:kernel_dump_stacktrace():   00000000001152BF
DEBUG    | src/arch/x86_64/kernel/panic.c:39:kernel_dump_stacktrace():   000000000010935B
```
After:
```
$ ./tools/fix-stacktrace.py build/x86_64/symbols.txt log/debug.log
[...]
DEBUG    | …
```
=> tools: add script to fix stacktrace in log files

src/libc/putchar.c, src/libc/willos/log.c
This patch fixes a bug where userland debug logs were not written correctly because `serial_print()` failed to write the correct data (due to `strlen()`).
=> libc: add null char when writing single chars

Makefile, README.md, include/stdlib.h, include/string.h, src/arch/x86_64/kernel/kmain.c, src/arch/x86_64/kernel/panic.c, src/arch/x86_64/kernel/panic.h, src/libc/string/strchrnul.c, src/libc/strtol.c, tools/fix-stacktrace.py
Fixes https://github.com/willdurand/willOS/issues/275
---
=> kernel: load debug symbols as a grub module and use them in kernel stacktraces

include/stdlib.h, src/libc/abort.c
This PR adds a new `abort()` function in the libc (only). It should probably use a syscall eventually.
=> libc: add initial implementation of the `abort()` function

.circleci/config.yml, Makefile, userland/boot-and-exit/Makefile, userland/testsuite/Makefile, userland/testsuite/main.c
This program should run some tests instead of not doing anything given that we
use it in the 'run-test' command. Let's port some of the 'selftest' test cases
into it.
=> build: userland: rename boot-and-exit to testsuite

.circleci/config.yml, src/arch/x86_64/kernel/kmain.c, src/arch/x86_64/kshell/kshell.c, src/arch/x86_64/kshell/kshell.h, src/arch/x86_64/kshell/power_off.c
This allows to pass arguments to `kshell_init()` in addition to reusing the
exact same code for two code paths. When arguments are passed to the kshell,
the system is powered off after having handled the different arguments.
The idea is to be able to tell the kshell to run some of its built-in commands
automatically, and then the system is powered off (abruptly). In this PR, the
code to run `selftest` has been added and a new `poweroff` built-in command
has been introduced to.. power off the system.
=> Invoke built-in commands in kshell via the GRUB cmdline

src/kernel/kshell/kshell.c
This is needed to be able to support backspaces on a serial connection with minicom for instance. This will be required for raspi3 support given that there won't be a screen available at the beginning.
=> kernel: kshell: handle different backspaces

src/kernel/sys/k_write.c
This makes the `k_write()` implementation arch-agnostic.
=> kernel: sys: move k_write to src/kernel/sys/

src/kernel/kshell/kshell.c
We only want to power off the system after having run the self tests.
=> kernel: kshell: do not power off system when kshell receives arguments

.gitmodules
This is needed to use fctvprintf(), which isn't implemented in the upstream library.
=> external: switch to printf fork

src/kernel/kmain.c
This would reveal a bug or that heap memory hasn't been setup correctly (also a bug).
=> kernel: kmain: panic when we cannot copy the original command line

.gitmodules, Doxyfile, Makefile, README.md, src/kernel/README.md, src/kernel/arch/aarch32/board/licheepi-nano/README.md, src/kernel/arch/aarch64/board/raspi3/README.md, src/libc/README.md, src/userland/README.md, src/userland/init/README.md, tools/doxygenify-md-files.py
It is still Doxygen but it is now themed with
https://github.com/jothepro/doxygen-awesome-css, which is a huuuuge
improvement over the built-in Doxygen theme.
I also found a way to better link the different README.md files by using
HTML comments with special Doxygen directives. It isn't super clean but
it isn't too bad either, and that works.
=> build: refactor how docs are generated

Doxyfile, tools/doxygen-todos.py, tools/doxygenify-md-files.py
Fixes https://github.com/willdurand/ArvernOS/issues/460
---
In order to create a TODO List page, we need to support the special
Doxygen syntax for TODOs. Given this is Doxygen-specific, we use a
Doxygen filter to modify the source on the fly.
=> docs: add a doxygen filter to handle TODOs

include/kernel/logging.h
This was introduced in 22496363fc369233e8964aebca9e2f208b116fff but
something was wrong and I missed it. Should be better now.
=> kernel: logging: fix timestamp used in INFO/WARN messages

src/kernel/arch/aarch64/kmain.h
Fixes https://github.com/willdurand/ArvernOS/issues/503
=> kernel: aarch64: fix kmain() declaration

src/kernel/arch/x86_64/arch/kernel.c
Fixes https://github.com/willdurand/ArvernOS/issues/542
=> kernel: x86_64: fix compilation error in non-selfhosting mode

include/kernel/sys/k_syscall.h, include/libc/fcntl.h, include/libc/sys/syscall.h, src/kernel/sys/k_openat.c, src/kernel/sys/k_syscall.c, src/libc/sys/openat.c
This implementation only handles AT_FDCWD, which behaves like open().
=> kernel: sys: add openat() syscall stub-ish

include/kernel/net/net.h, src/kernel/arch/x86_64/drivers/rtl8139.c, src/kernel/kshell/net.c, src/kernel/net/arp.c, src/kernel/net/net.c
- The driver does not need to have a `receive` function, it can call a
method of the interface.
- Add hardware type on both `net_driver_t` and `net_interface_t` because
that is useful and we only support Ethernet 802.3 so far.
=> kernel: net: slightly refactor the network interfaces

Makefile, include/libc/assert.h
- add `DEBUG_MODE` constant so that `assert()` is only implemented for
libk in debug mode
- only generate `.gdbinit` when `make gdb` is used
- add `-ggdb` to debug CFLAGS when `make gdb` is used
=> build: improve makefile config for debug mode

src/kernel/arch/x86_64/kmain.c
This allows to test the kernel with `bochs`.
=> kernel: x86_64: skip network init if pci device is missing

src/kernel/arch/x86_64/arch/proc.c, src/kernel/arch/x86_64/asm/proc.asm, src/kernel/kshell/selftest.c
=> kernel: x86_64: do not use iretq for context switching (yet)

Makefile, include/kernel/core/elf.h, src/kernel/core/elf.c
Kinda fixes https://github.com/willdurand/ArvernOS/issues/540
---
This is not quite correct for non-x86_64 architectures but that's a start at least...
=> kernel: core: move ELF loader to shared code

include/libc/ubsan.h, src/libc/ubsan.c
There is no reason to have all the structures defined since they are not used at all.
=> libc: simplify ubsan code
